Updated Nuke to 9.0.4 (#176)
There are some breaking changes in Nuke 9.0.4 and if host are using
9.0.1 and confix.nuke package is used as satelite then
MissingMethodException: Method not found error is thrown